name: wide
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  http: ^1.2.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  camera: ^0.10.5+9
  path_provider: ^2.1.3
  path: ^1.9.0
  expandable: ^5.0.1
  expandable_text: ^2.3.0
  vibration: ^1.8.4
  video_player: ^2.8.6
  appinio_video_player: ^1.2.2
  voice_message_package: ^2.2.1
  image_picker: ^1.1.1
  chatview: ^1.3.1
  flutter_secure_storage: ^9.0.0
  camerawesome: ^2.0.1
  file_utils: ^1.0.1
  media: ^0.0.2
  media_kit: ^1.1.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/images/profile/
    - assets/icons/post/category.svg
    - assets/images/post/
    - assets/images/companies/
    - assets/icons/profile/
    - assets/icons/tab_bar/plus_icon.svg
    # - assets/icons/home/return.svg
    # - assets/images/home/logo.png
    # - assets/icons/home/home_icon.svg
    # - assets/icons/profile/bluesave.png
    - assets/icons/auth/
    - assets/images/home/
    # - assets/images/profile/menu.svg
    - assets/icons/post/
    - assets/icons/home/
    - assets/icons/tab_bar/
    # - assets/icons/tab_bar/notification.svg
    # - assets/icons/auth/auth_logo.svg
    # - assets/icons/auth/google.svg
    # - assets/icons/auth/facebook.svg
    # - assets/icons/auth/eye_icon.svg
    # - assets/icons/auth/off_eye_icon.svg
    # - assets/icons/home/plus.svg
    # - assets/icons/tab_bar/home_icon.svg
    # - assets/icons/tab_bar/search_icon.svg

    - assets/icons/home/home_icon.svg
    - assets/icons/auth/apple.svg
    - assets/icons/

  fonts:
    - family: Geometria
      fonts:
        - asset: assets/fonts/Geometria.ttf
        # - asset: assets/fonts/Geometria-Medium.ttf
        # - asset: assets/fonts/Geometria-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
